### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Kamran95** [Ngahu/Electron-Flask-App#1]
i cloned your project installed electron-builder
it works fine in development mode but gives following error in production mode 
**Error**
** A JavaScript error occurred in the main process **
Uncaught Exception:
Error: /Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file 'engine.py': [Errno 2] No such file or directory

    at PythonShell.parseError (/Applications/electron-quick-start.app/Contents/Resources/app.asar/node_modules/python-shell/index.js:240:21)
    at terminateIfNeeded (/Applications/electron-quick-start.app/Contents/Resources/app.asar/node_modules/python-shell/index.js:121:32)
    at Socket.<anonymous> (/Applications/electron-quick-start.app/Contents/Resources/app.asar/node_modules/python-shell/index.js:104:13)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Kamran95** [comment]
i have been searching for solution since long time my product is stuck on same error cal you please guide me if you come up with some solution
